# Netlify configuration for Hawaii SNAP visualization dashboard

[build]
  # Base directory for the build
  base = "/"

  # Build command - install minimal dependencies and generate JSON data
  command = "pip install -r requirements-build.txt && python scripts/prepare_web_data.py"

  # Directory to deploy (contains index.html)
  publish = "web"

# Python version for build
[build.environment]
  PYTHON_VERSION = "3.11"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (optional)
# [[redirects]]
#   from = "/404"
#   to = "/404.html"
#   status = 404
